export type Grade = 3 | 4 | 5;
export type DayKind = "alice" | "walk" | "rest" | "summit" | "depart";

export type Waypoint = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  kind: "trailhead" | "camp" | "highlight" | "food" | "water";
};

export type DayPlan = {
  id: string;
  dayLabel: string;
  kind: DayKind;
  title: string;
  from: string;
  to: string;
  km: number;
  hours: string;
  section: string;
  grade?: Grade;
  camp: string;
  waterCarryL: string;
  waterNote: string;
  food: string;
  highlights: string[];
  notes: string[];
  waypointId: string;
};

export const trip = {
  name: "Larapinta Trail 2027",
  walkers: ["Salvatore Prestianni", "James Saville"],
  direction: "East to west",
  season: "April–May 2027",
  walkStart: "Monday 12 April 2027",
  arriveAlice: "Saturday 10 April 2027",
  departAlice: "Sunday 2 May 2027",
  start: "Alice Springs Telegraph Station",
  finish: "Mt Sonder, then Redbank Gorge",
  trailKm: 231,
  walkingDays: 18,
  restDays: 2,
  aliceDays: 3,
  officialSource: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail",
};

export const sections: {
  id: number;
  name: string;
  from: string;
  to: string;
  km: number;
  grade: Grade;
  gradeLabel: string;
  officialNote: string;
}[] = [
  {
    id: 1,
    name: "Alice Springs Telegraph Station to Simpsons Gap",
    from: "Telegraph Station",
    to: "Simpsons Gap",
    km: 24.7,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Long distance with some steep ascents. Euro Ridge and Hat Hill Saddle are the early views.",
  },
  {
    id: 2,
    name: "Simpsons Gap to Jay Creek",
    from: "Simpsons Gap",
    to: "Jay Creek",
    km: 26.2,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Long ridgeline walking. Jay Creek has no public vehicle access — walk in from Simpsons Gap or Standley Chasm only.",
  },
  {
    id: 3,
    name: "Jay Creek to Standley Chasm",
    from: "Jay Creek",
    to: "Standley Chasm",
    km: 13.6,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Steep, rugged country. A high route and a lower creek route exist. Standley Chasm is privately run — entry and camping fees apply.",
  },
  {
    id: 4,
    name: "Standley Chasm to Birthday Waterhole",
    from: "Standley Chasm",
    to: "Birthday Waterhole / 4–5 Junction",
    km: 17.9,
    grade: 5,
    gradeLabel: "Difficult",
    officialNote: "One of the hardest sections. Brinkley Bluff is the standout high camp.",
  },
  {
    id: 5,
    name: "Birthday Waterhole to Hugh Gorge",
    from: "4–5 Junction",
    to: "Hugh Gorge",
    km: 14.9,
    grade: 5,
    gradeLabel: "Difficult",
    officialNote: "Razorback Ridge country. Spectacular and slow. Hugh Gorge can hold water after rain.",
  },
  {
    id: 6,
    name: "Hugh Gorge to Ellery Creek North",
    from: "Hugh Gorge",
    to: "Ellery Creek North",
    km: 28.9,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Longest east-side section. Split at Rocky Gully. Food drop is at Ellery Creek South, a short walk from the trail camp.",
  },
  {
    id: 7,
    name: "Ellery Creek North to Serpentine Gorge",
    from: "Ellery Creek North",
    to: "Serpentine Gorge",
    km: 12.8,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Shorter day with classic Central Australian geology. Optional swim at Ellery Creek Big Hole before leaving.",
  },
  {
    id: 8,
    name: "Serpentine Gorge to Serpentine Chalet Dam",
    from: "Serpentine Gorge",
    to: "Serpentine Chalet Dam",
    km: 13.8,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Well-supported high country with stone steps. USB charging at Serpentine Chalet.",
  },
  {
    id: 9,
    name: "Serpentine Chalet Dam to Ormiston Gorge",
    from: "Serpentine Chalet Dam",
    to: "Ormiston Gorge",
    km: 28.9,
    grade: 5,
    gradeLabel: "Difficult",
    officialNote: "Longest dry carry. NT Parks says split over two days and camp at Waterfall Gorge with enough water for two days. Counts Point looks onto Mt Sonder.",
  },
  {
    id: 10,
    name: "Ormiston Gorge to Finke River",
    from: "Ormiston Gorge",
    to: "Finke River",
    km: 8.9,
    grade: 3,
    gradeLabel: "Moderate",
    officialNote: "Easiest official section. Hilltop lookout and the dry Finke River bed.",
  },
  {
    id: 11,
    name: "Finke River to Redbank Gorge",
    from: "Finke River",
    to: "Redbank Gorge",
    km: 26.3,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Split at Rocky Bar Gap. Glen Helen access can change — check NT Parks current conditions before you walk.",
  },
  {
    id: 12,
    name: "Redbank Gorge to Mt Sonder return",
    from: "Redbank Gorge",
    to: "Mt Sonder and back",
    km: 15.8,
    grade: 4,
    gradeLabel: "Moderate to difficult",
    officialNote: "Out-and-back to the highest point on the trail. Pre-dawn start for sunrise on the summit is the classic finish.",
  },
];

export const waypoints: Waypoint[] = [
  { id: "telegraph", name: "Alice Springs Telegraph Station", lat: -23.67095, lng: 133.88508, kind: "trailhead" },
  { id: "wallaby", name: "Wallaby Gap", lat: -23.6764, lng: 133.7728, kind: "camp" },
  { id: "simpsons", name: "Simpsons Gap", lat: -23.67388, lng: 133.71956, kind: "camp" },
  { id: "mulga", name: "Mulga Camp", lat: -23.66474, lng: 133.6129, kind: "camp" },
  { id: "jay", name: "Jay Creek", lat: -23.7278, lng: 133.5042, kind: "camp" },
  { id: "standley", name: "Standley Chasm", lat: -23.71613, lng: 133.47015, kind: "food" },
  { id: "brinkley", name: "Brinkley Bluff", lat: -23.71082, lng: 133.39201, kind: "camp" },
  { id: "junction45", name: "4–5 Junction / Birthday Waterhole", lat: -23.72529, lng: 133.34284, kind: "water" },
  { id: "hugh", name: "Hugh Gorge", lat: -23.67107, lng: 133.2722, kind: "camp" },
  { id: "rocky-gully", name: "Rocky Gully", lat: -23.76163, lng: 133.1693, kind: "camp" },
  { id: "ellery", name: "Ellery Creek Big Hole", lat: -23.77684, lng: 133.07341, kind: "food" },
  { id: "serpentine", name: "Serpentine Gorge", lat: -23.75174, lng: 132.97861, kind: "camp" },
  { id: "chalet", name: "Serpentine Chalet Dam", lat: -23.72551, lng: 132.91062, kind: "water" },
  { id: "waterfall", name: "Waterfall Gorge", lat: -23.68717, lng: 132.82522, kind: "camp" },
  { id: "ormiston", name: "Ormiston Gorge", lat: -23.63225, lng: 132.7264, kind: "food" },
  { id: "finke", name: "Finke River", lat: -23.5897, lng: 132.679, kind: "camp" },
  { id: "rocky-bar", name: "Rocky Bar Gap", lat: -23.60865, lng: 132.60275, kind: "camp" },
  { id: "redbank", name: "Redbank Gorge", lat: -23.57758, lng: 132.51861, kind: "trailhead" },
  { id: "sonder", name: "Mt Sonder", lat: -23.6604, lng: 132.433, kind: "highlight" },
  { id: "alice", name: "Alice Springs", lat: -23.698, lng: 133.8807, kind: "trailhead" },
];

export const days: DayPlan[] = [
  {
    id: "a1",
    dayLabel: "Alice 1",
    kind: "alice",
    title: "Fly in and meet in Alice",
    from: "Perth / Brisbane",
    to: "Alice Springs",
    km: 0,
    hours: "Travel day",
    section: "—",
    camp: "Alice Springs hotel or Airbnb",
    waterCarryL: "—",
    waterNote: "Town water. Start hydrating hard — you will be walking in dry country within 48 hours.",
    food: "Buy remaining trail food at Coles, Woolworths, or IGA. Lone Dingo for last-minute gear.",
    highlights: [
      "Salvatore lands from Perth (PER → ASP). Typical options: Airnorth direct (~2h 40m on some weekdays) or Qantas via Adelaide (about 5–7 hours).",
      "James lands from Brisbane. Qantas and Virgin both fly BNE–ASP nonstop in about 3 hours 15 minutes.",
      "Airport is 15 km from town. Use the airport shuttle or a taxi to the same accommodation.",
    ],
    notes: [
      "Book flights to arrive on the same afternoon if you can. Keep a later backup in case of missed connections.",
      "2027 domestic schedules are not published yet. Search from about August–October 2026, when airlines usually release the April–May 2027 timetable.",
      "Arrive Saturday 10 April 2027 so you have Sunday for packing. The walk starts Monday 12 April.",
    ],
    waypointId: "alice",
  },
  {
    id: "a2",
    dayLabel: "Alice 2",
    kind: "alice",
    title: "Pack drops, permits, key",
    from: "Alice Springs",
    to: "Alice Springs",
    km: 0,
    hours: "Logistics day",
    section: "—",
    camp: "Alice Springs",
    waterCarryL: "—",
    waterNote: "Fill and test every bottle and bladder tonight.",
    food: "Commercial support delivers empty 50 L containers to your accommodation. Pack three drops: Standley Chasm, Ellery Creek South, Ormiston Gorge.",
    highlights: [
      "Confirm NT Parks bookings: visitor pass, walking-trail fee, and every campsite night at parkbookings.nt.gov.au.",
      "Collect or receive the food-storeroom key. Official Parks rooms at Ellery Creek South, Serpentine Gorge and Ormiston need this key. Standley Chasm is a private store and does not use the Parks key.",
      "Meet your transfer company and lock the Redbank Gorge afternoon pickup for Day 20.",
    ],
    notes: [
      "Tourism Central Australia (Todd Mall) issues the Parks storeroom key if your package does not include it: $50 refundable deposit plus a $10 admin fee (2026 figures — confirm for 2027).",
      "Standley Chasm is private. Pay their entry and camping fees directly: standleychasm.com.au or 08 8956 7440.",
      "Write the trip plan down for a home contact. NT Parks says do not rely on mobile phones.",
    ],
    waypointId: "alice",
  },
  {
    id: "1",
    dayLabel: "Day 1",
    kind: "walk",
    title: "Onto the range",
    from: "Telegraph Station",
    to: "Wallaby Gap",
    km: 13.9,
    hours: "5–6 h",
    section: "1",
    grade: 4,
    camp: "Wallaby Gap",
    waterCarryL: "3–4 L",
    waterNote: "Town tap at the Telegraph Station, then a ranger tank at Wallaby Gap (13.9 km).",
    food: "Carry days 1–5 from Alice. Next resupply is Standley Chasm on Day 5.",
    highlights: [
      "Official eastern start of the Larapinta Trail on Arrernte Country.",
      "Euro Ridge and Hat Hill Saddle give the first long views over Alice and the Heavitree Range.",
      "Easy first camp to settle packs, feet, and water discipline.",
    ],
    notes: [
      "Taxi or a 3 km walk along the Todd riverbed from town. Commercial operators generally do not drop at the Telegraph Station.",
      "Start early. April days can still reach the high 20s.",
    ],
    waypointId: "wallaby",
  },
  {
    id: "2",
    dayLabel: "Day 2",
    kind: "walk",
    title: "Finish Section 1",
    from: "Wallaby Gap",
    to: "Simpsons Gap",
    km: 10.8,
    hours: "4–5 h",
    section: "1",
    grade: 4,
    camp: "Simpsons Gap",
    waterCarryL: "3 L",
    waterNote: "Ranger tank at Simpsons Gap, 10.8 km from Wallaby Gap.",
    food: "Cooking from the Alice carry.",
    highlights: [
      "Simpsons Gap is a major visitor site — black-footed rock wallabies at dusk if you sit quietly.",
      "Good water and a proper trailhead shelter.",
      "Short enough day to check hot spots on feet before the longer Section 2.",
    ],
    notes: ["Tourist vehicles use Simpsons Gap. Camp only in the booked designated site."],
    waypointId: "simpsons",
  },
  {
    id: "3",
    dayLabel: "Day 3",
    kind: "walk",
    title: "Spinifex ridgelines",
    from: "Simpsons Gap",
    to: "Mulga Camp",
    km: 16.4,
    hours: "6–7 h",
    section: "2",
    grade: 4,
    camp: "Mulga Camp",
    waterCarryL: "4 L",
    waterNote: "Next tank is Mulga Camp, 16.4 km. No reliable water in between.",
    food: "Alice carry.",
    highlights: [
      "Classic West MacDonnell ridgeline — red quartzite, spinifex, and long views west.",
      "Quieter once you leave the Simpsons Gap car park behind.",
    ],
    notes: ["April–May still has high UV. Long sleeves and a brimmed hat are official NT Parks advice."],
    waypointId: "mulga",
  },
  {
    id: "4",
    dayLabel: "Day 4",
    kind: "walk",
    title: "Into Jay Creek",
    from: "Mulga Camp",
    to: "Jay Creek",
    km: 9.8,
    hours: "3.5–4.5 h",
    section: "2",
    grade: 4,
    camp: "Jay Creek",
    waterCarryL: "3 L",
    waterNote: "Ranger tank at Jay Creek. USB charging is available at this shelter.",
    food: "Alice carry. Eat a heavier dinner — tomorrow is the Standley climb.",
    highlights: [
      "Shorter day after yesterday’s ridge.",
      "Jay Creek shelter is a good charge-up point for inReach / phone / headtorch.",
    ],
    notes: [
      "NT Parks current conditions: no public vehicle or pedestrian access to Jay Creek from Hamilton Downs Youth Camp Road. Walkers reach it only via the trail.",
    ],
    waypointId: "jay",
  },
  {
    id: "5",
    dayLabel: "Day 5",
    kind: "walk",
    title: "Standley Chasm",
    from: "Jay Creek",
    to: "Standley Chasm",
    km: 13.6,
    hours: "5.5–7 h",
    section: "3",
    grade: 4,
    camp: "Standley Chasm (private)",
    waterCarryL: "4 L",
    waterNote: "Bore tap at Standley Chasm, 13.6 km. Treat it the same as tank water.",
    food: "Food drop 1. Open the Standley container, eat fresh-from-drop food, pack days 7–11.",
    highlights: [
      "High route is steeper and the better walk if both of you are feeling strong.",
      "Angkerle Atwatye / Standley Chasm — a private Arrernte-owned site with a cafe, showers, and camping.",
      "First real wash since Alice.",
    ],
    notes: [
      "Pay Standley Chasm entry even if you are only passing through on Sections 3 and 4.",
      "Confirm cafe and kiosk hours before you count on a cooked meal.",
    ],
    waypointId: "standley",
  },
  {
    id: "6",
    dayLabel: "Day 6",
    kind: "rest",
    title: "Rest at Standley",
    from: "Standley Chasm",
    to: "Standley Chasm",
    km: 0,
    hours: "Rest",
    section: "—",
    camp: "Standley Chasm (private)",
    waterCarryL: "—",
    waterNote: "Rehydrate. Wash bottles. Fill tomorrow’s load tonight.",
    food: "Cafe meals plus food from Drop 1. Do not start Section 4 with a light breakfast.",
    highlights: [
      "Zero-kilometre day before the first Grade 5 section.",
      "Sort feet, tape, stove fuel, and the next five days of food.",
      "Walk into the chasm at midday when the walls glow orange — that is the postcard moment.",
    ],
    notes: ["This rest is deliberate. Sections 4 and 5 are the hardest pair on the official grade table."],
    waypointId: "standley",
  },
  {
    id: "7",
    dayLabel: "Day 7",
    kind: "walk",
    title: "Brinkley Bluff",
    from: "Standley Chasm",
    to: "Brinkley Bluff",
    km: 9,
    hours: "5–7 h",
    section: "4",
    grade: 5,
    camp: "Brinkley Bluff",
    waterCarryL: "5–6 L",
    waterNote: "No tank on the bluff. Carry camp and breakfast water from Standley. Next tank is 4–5 Junction (17.9 km from Standley).",
    food: "Drop 1 carry.",
    highlights: [
      "First Grade 5 day. Slow, rocky, and worth it.",
      "Brinkley Bluff is one of the best sunset and sunrise camps on the whole trail.",
      "360° range views if the April sky is clear.",
    ],
    notes: [
      "Book Brinkley Bluff as a designated Category B camp.",
      "Nights in May can still drop toward single figures. A -5 °C bag is the official winter advice; April is milder but the bluff is exposed.",
    ],
    waypointId: "brinkley",
  },
  {
    id: "8",
    dayLabel: "Day 8",
    kind: "walk",
    title: "Birthday Waterhole",
    from: "Brinkley Bluff",
    to: "4–5 Junction",
    km: 8.9,
    hours: "4–5 h",
    section: "4",
    grade: 5,
    camp: "4–5 Junction / Birthday Waterhole",
    waterCarryL: "3–4 L",
    waterNote: "Ranger tank at 4–5 Junction, 17.9 km from Standley in total.",
    food: "Drop 1 carry.",
    highlights: [
      "Descent off Brinkley is steep and loose — poles help.",
      "Birthday Waterhole can hold water after late-wet-season rain. Treat any surface water.",
    ],
    notes: ["Section 4 official distance is 17.9 km Standley to Birthday Waterhole. You split it across Days 7 and 8."],
    waypointId: "junction45",
  },
  {
    id: "9",
    dayLabel: "Day 9",
    kind: "walk",
    title: "Razorback to Hugh Gorge",
    from: "4–5 Junction",
    to: "Hugh Gorge",
    km: 14.9,
    hours: "7–10 h",
    section: "5",
    grade: 5,
    camp: "Hugh Gorge",
    waterCarryL: "4–5 L",
    waterNote: "Ranger tank at Hugh Gorge, 14.9 km. USB charging at the shelter.",
    food: "Drop 1 carry. Tomorrow is a long Section 6 split.",
    highlights: [
      "Officially Grade 5 and many walkers’ favourite section.",
      "Razorback Ridge — narrow quartzite, big air, slow walking.",
      "Hugh Gorge waterhole is a possible soak if recent rain has filled it. After rain you may wade.",
    ],
    notes: [
      "This is a short-distance, long-time day. Do not judge it by kilometres.",
      "Pack liner matters more than a pack cover if the gorge is wet.",
    ],
    waypointId: "hugh",
  },
  {
    id: "10",
    dayLabel: "Day 10",
    kind: "walk",
    title: "Hugh Gorge to Rocky Gully",
    from: "Hugh Gorge",
    to: "Rocky Gully",
    km: 15.3,
    hours: "6–7 h",
    section: "6",
    grade: 4,
    camp: "Rocky Gully",
    waterCarryL: "4 L",
    waterNote: "Ranger tank at Rocky Gully, 15.3 km.",
    food: "Drop 1 carry. Ellery resupply tomorrow.",
    highlights: [
      "Section 6 is 28.9 km official — too long as one day with full packs, so you split it here.",
      "More open range walking after the razorback.",
    ],
    notes: ["Keep some dinner flexibility. If you arrive early, wash and repair rather than pushing to Ellery."],
    waypointId: "rocky-gully",
  },
  {
    id: "11",
    dayLabel: "Day 11",
    kind: "walk",
    title: "Ellery Creek Big Hole",
    from: "Rocky Gully",
    to: "Ellery Creek North",
    km: 13.6,
    hours: "5–6 h",
    section: "6",
    grade: 4,
    camp: "Ellery Creek North",
    waterCarryL: "3–4 L",
    waterNote: "Ranger tank at Ellery Creek North, 13.6 km. Big Hole is a swimming waterhole, not your drinking plan.",
    food: "Food drop 2 at Ellery Creek South (locked Parks storeroom — key required). Pack days 12–15.",
    highlights: [
      "Ellery Creek Big Hole is one of the trail’s best swims, especially in April–May when the water is still cold but the air is kind.",
      "Official food-drop room is in the south ablution block, with CCTV.",
    ],
    notes: [
      "North is the trail camp. South is the day-use / food-drop side. Budget extra walking time to the storeroom.",
      "Ellery Creek South camping is a separate Category B booking if you choose to stay south instead.",
    ],
    waypointId: "ellery",
  },
  {
    id: "12",
    dayLabel: "Day 12",
    kind: "walk",
    title: "Serpentine Gorge",
    from: "Ellery Creek North",
    to: "Serpentine Gorge",
    km: 12.8,
    hours: "5–5.5 h",
    section: "7",
    grade: 4,
    camp: "Serpentine Gorge",
    waterCarryL: "3–4 L",
    waterNote: "Ranger tank at the Serpentine Gorge Larapinta campsite, 12.0–12.8 km depending on the exact north/south start.",
    food: "Drop 2 carry.",
    highlights: [
      "Shorter recovery day after Section 6.",
      "Folded quartzite and a side walk to the gorge lookout if you have daylight.",
    ],
    notes: [
      "There is also an official food room at Serpentine Gorge (shipping container near the car park). You do not need it if Ellery was stocked.",
    ],
    waypointId: "serpentine",
  },
  {
    id: "13",
    dayLabel: "Day 13",
    kind: "walk",
    title: "Serpentine Chalet Dam",
    from: "Serpentine Gorge",
    to: "Serpentine Chalet Dam",
    km: 13.8,
    hours: "5–5.5 h",
    section: "8",
    grade: 4,
    camp: "Serpentine Chalet Dam",
    waterCarryL: "4 L",
    waterNote: "Ranger tank at Serpentine Chalet Dam, 13.8 km. USB charging at the shelter.",
    food: "Drop 2 carry. Tomorrow you take two days of food and a heavy water load onto Section 9.",
    highlights: [
      "High points on Section 8 are some of the cleanest constructed trail on the Larapinta.",
      "Charge devices tonight. Section 9 is remote.",
    ],
    notes: ["Prep 6 L+ of water each for the Waterfall Gorge dry camp. This is the official two-day carry."],
    waypointId: "chalet",
  },
  {
    id: "14",
    dayLabel: "Day 14",
    kind: "walk",
    title: "Section 9 dry camp",
    from: "Serpentine Chalet Dam",
    to: "Waterfall Gorge",
    km: 12,
    hours: "5–7 h",
    section: "9",
    grade: 5,
    camp: "Waterfall Gorge",
    waterCarryL: "6 L+",
    waterNote: "No tank at Waterfall Gorge. Official advice: carry enough water for two days. Next reliable water is Ormiston, 28.9 km from the Chalet.",
    food: "Drop 2 carry. Keep Day 15 food and a hot breakfast.",
    highlights: [
      "NT Parks recommended split for Grade 5 Section 9.",
      "Waterfall Gorge is a designated camp. After rain the gorge can hold water — treat it, and do not count on it.",
    ],
    notes: [
      "This is the heaviest pack day of the trip. Start early.",
      "April heat makes the 6 L carry non-negotiable. Do not walk Section 9 as a single 28.9 km day in this season.",
    ],
    waypointId: "waterfall",
  },
  {
    id: "15",
    dayLabel: "Day 15",
    kind: "walk",
    title: "Counts Point to Ormiston",
    from: "Waterfall Gorge",
    to: "Ormiston Gorge",
    km: 16.9,
    hours: "6–8 h",
    section: "9",
    grade: 5,
    camp: "Ormiston Gorge",
    waterCarryL: "3–4 L remaining",
    waterNote: "Rainwater / visitor tanks at Ormiston Gorge. You should arrive with water still in the bottles.",
    food: "Food drop 3 in the main building near the kiosk (key + CCTV). Pack days 17–20.",
    highlights: [
      "Counts Point — the view to Mt Sonder that most end-to-end walkers remember.",
      "Ormiston has a kiosk, showers in the visitor area, and a Category C campground.",
      "Ghost Gum Walk and a cold gorge swim if you have legs left.",
    ],
    notes: ["Ormiston camping is Category C ($20 adult in the 2026 fee table, not the $10 Category B rate). Book it as such."],
    waypointId: "ormiston",
  },
  {
    id: "16",
    dayLabel: "Day 16",
    kind: "rest",
    title: "Rest at Ormiston",
    from: "Ormiston Gorge",
    to: "Ormiston Gorge",
    km: 0,
    hours: "Rest",
    section: "—",
    camp: "Ormiston Gorge (Category C)",
    waterCarryL: "—",
    waterNote: "Drink freely. Wash. Refill for the easy Section 10.",
    food: "Kiosk plus Drop 3. Eat the heavy food here.",
    highlights: [
      "Second planned rest before the western finish.",
      "Optional Pound Walk if you want a light day-pack side trip.",
      "Confirm the Day 20 Redbank pickup time by satellite message if you have not already.",
    ],
    notes: ["Glen Helen Lodge has been listed as closed in recent NT Parks condition updates. Do not plan a bed or meal there unless 2027 conditions say it is open."],
    waypointId: "ormiston",
  },
  {
    id: "17",
    dayLabel: "Day 17",
    kind: "walk",
    title: "Finke River",
    from: "Ormiston Gorge",
    to: "Finke River",
    km: 8.9,
    hours: "3.5–4 h",
    section: "10",
    grade: 3,
    camp: "Finke River",
    waterCarryL: "3 L",
    waterNote: "Ranger tank at Finke River, 8.9 km.",
    food: "Drop 3 carry.",
    highlights: [
      "Only official Grade 3 section — a recovery walk.",
      "Hilltop lookout and the dry Finke, often called one of the world’s oldest rivers.",
    ],
    notes: ["Short day on purpose after rest. Use the afternoon to sort the Sonder summit kit."],
    waypointId: "finke",
  },
  {
    id: "18",
    dayLabel: "Day 18",
    kind: "walk",
    title: "Rocky Bar Gap",
    from: "Finke River",
    to: "Rocky Bar Gap",
    km: 14.7,
    hours: "5.5–6.5 h",
    section: "11",
    grade: 4,
    camp: "Rocky Bar Gap",
    waterCarryL: "4 L",
    waterNote: "Ranger tank at Rocky Bar Gap, 14.7 km from Finke.",
    food: "Drop 3 carry.",
    highlights: [
      "Section 11 official distance is 26.3 km. You split it so Day 19 stays short before the summit.",
      "Western Heavitree Range — Sonder starts to dominate the skyline.",
    ],
    notes: ["Check NT Parks conditions for any Glen Helen reroute on this section."],
    waypointId: "rocky-bar",
  },
  {
    id: "19",
    dayLabel: "Day 19",
    kind: "walk",
    title: "Redbank Gorge",
    from: "Rocky Bar Gap",
    to: "Redbank Gorge",
    km: 11.1,
    hours: "4–5 h",
    section: "11",
    grade: 4,
    camp: "Redbank Gorge",
    waterCarryL: "3–4 L",
    waterNote: "Ranger tank at Redbank Gorge, 11.1 km.",
    food: "Drop 3 carry. Pack a summit breakfast and snacks only for tomorrow. Leave the heavy kit in camp.",
    highlights: [
      "Finish the through-walk at the official western trailhead.",
      "Redbank Gorge swim if the water is in — cold in April–May.",
      "Early night. Pre-dawn Sonder start is the point of Day 20.",
    ],
    notes: ["Transfer pickup is after you return from the summit, not this afternoon."],
    waypointId: "redbank",
  },
  {
    id: "20",
    dayLabel: "Day 20",
    kind: "summit",
    title: "Mt Sonder sunrise, then home",
    from: "Redbank Gorge",
    to: "Mt Sonder return, transfer to Alice",
    km: 15.8,
    hours: "6 h walking + 2–2.5 h transfer",
    section: "12",
    grade: 4,
    camp: "Alice Springs",
    waterCarryL: "3–4 L",
    waterNote: "Day pack only. Tank at Redbank before you start.",
    food: "Summit snacks. First real meal is back in Alice.",
    highlights: [
      "Official end of the Larapinta: the summit of Mt Sonder / Rwetyepme, highest point on the trail.",
      "Leave camp in the dark with headtorches. Sunrise from the top is the finish you walked 230 km for.",
      "Commercial transfer from the Redbank car park back to Alice Springs (about 2–2.5 hours).",
    ],
    notes: [
      "Book an afternoon pickup, not a morning one. You will not be down before late morning.",
      "LTTS and Larapinta Express both run Redbank transfers. Duo E2E packages in 2026 were about $690 for two people including three food drops and the transfer — confirm 2027 pricing.",
      "Celebrate in Alice. Do not book a same-night flight to Perth or Brisbane.",
    ],
    waypointId: "sonder",
  },
  {
    id: "p1",
    dayLabel: "Alice out",
    kind: "depart",
    title: "Fly home",
    from: "Alice Springs",
    to: "Perth / Brisbane",
    km: 0,
    hours: "Travel day",
    section: "—",
    camp: "—",
    waterCarryL: "—",
    waterNote: "—",
    food: "Town food. Return unused stove fuel if the airline will not take it.",
    highlights: [
      "Return the storeroom key and collect the $50 deposit.",
      "Salvatore: ASP → PER (Airnorth direct or Qantas via Adelaide).",
      "James: ASP → Brisbane nonstop on Qantas or Virgin.",
    ],
    notes: [
      "Keep this as a full buffer day. Afternoon flights are safer after a 20-day walk.",
      "If you want Uluru, add nights after the walk — it is more than 400 km from Alice and is not on this itinerary.",
    ],
    waypointId: "alice",
  },
];

export const waterPoints = [
  { location: "Alice Springs Telegraph Station", type: "Town tap", kmFromLast: 0, section: "1" },
  { location: "Wallaby Gap", type: "Ranger tank", kmFromLast: 13.9, section: "1" },
  { location: "Simpsons Gap", type: "Ranger tank", kmFromLast: 10.8, section: "1–2" },
  { location: "Mulga Camp", type: "Ranger tank", kmFromLast: 16.4, section: "2" },
  { location: "Jay Creek", type: "Ranger tank", kmFromLast: 9.8, section: "2–3" },
  { location: "Standley Chasm", type: "Bore tap", kmFromLast: 13.6, section: "3–4" },
  { location: "4–5 Junction", type: "Ranger tank", kmFromLast: 17.9, section: "4–5" },
  { location: "Hugh Gorge", type: "Ranger tank", kmFromLast: 14.9, section: "5–6" },
  { location: "Rocky Gully", type: "Ranger tank", kmFromLast: 15.3, section: "6" },
  { location: "Ellery Creek North", type: "Ranger tank", kmFromLast: 13.6, section: "6–7" },
  { location: "Serpentine Gorge camp", type: "Ranger tank", kmFromLast: 12.0, section: "7–8" },
  { location: "Serpentine Chalet Dam", type: "Ranger tank", kmFromLast: 13.8, section: "8–9" },
  { location: "Ormiston Gorge", type: "Rainwater / visitor tanks", kmFromLast: 28.9, section: "9–10" },
  { location: "Finke River", type: "Ranger tank", kmFromLast: 8.9, section: "10–11" },
  { location: "Rocky Bar Gap", type: "Ranger tank", kmFromLast: 14.7, section: "11" },
  { location: "Redbank Gorge", type: "Ranger tank", kmFromLast: 11.1, section: "11–12" },
];

export const fees = [
  { item: "NT Parks Visitor Pass — 1 month", each: "$45", note: "Required for interstate visitors. 2-week pass is $30 if your Alice buffers fit. NT residents are exempt." },
  { item: "Larapinta walking-trail fee", each: "$125", note: "Capped at $125 for 6+ consecutive days. Separate from camping." },
  { item: "Category B camps (most trail camps)", each: "$10 / night", note: "15 Parks nights in this itinerary, not counting Standley or Ormiston." },
  { item: "Ormiston Gorge camp", each: "$20 / night", note: "Category C. Two nights: arrive Day 15 and rest Day 16." },
  { item: "Standley Chasm unpowered camp", each: "$25.50 then $16.50", note: "Per person. First night $25.50, extra night $16.50. Entry is included. Book standleychasm.com.au." },
  { item: "Food-storeroom key", each: "$50 deposit + $10 fee", note: "Tourism Central Australia, Todd Mall. Deposit back when the key is returned." },
];

export type CostPayer = "james" | "salvatore";

export type CostLine = {
  item: string;
  each: string;
  pairLow: number;
  pairMid: number;
  pairHigh: number;
  note: string;
  payer: CostPayer;
};

export const budget = {
  currency: "AUD",
  asOf: "August 2026 advertised prices, planned for April–May 2027. Flights and hotels move; Parks fees are official 2026 rates.",
  party: 2,
  nightsAlice: 3,
  trailFoodDays: 20,
  lowTotal: 4500,
  midTotal: 5500,
  highTotal: 6800,
  split: {
    james: {
      name: "James Saville",
      pays: "Brisbane ⇄ Alice Springs return flight only",
      low: 570,
      mid: 750,
      high: 970,
    },
    salvatore: {
      name: "Salvatore Prestianni",
      pays: "His Perth flights plus every other trip cost for both walkers",
      low: 3930,
      mid: 4750,
      high: 5830,
    },
  },
  groups: [
    {
      name: "Flights",
      lines: [
        {
          item: "Salvatore · Perth ⇄ Alice return",
          each: "Airnorth from ~$775 return; Qantas via Adelaide often $970–$1,330",
          pairLow: 775,
          pairMid: 1000,
          pairHigh: 1330,
          note: "Direct Airnorth is the cheap/fast option (~2h 40m). Qantas via Adelaide is the reliable backup.",
          payer: "salvatore",
        },
        {
          item: "James Saville · Brisbane ⇄ Alice return",
          each: "Virgin from ~$570–$600 return; Qantas often $730–$970",
          pairLow: 570,
          pairMid: 750,
          pairHigh: 970,
          note: "James just needs to get to Alice Springs. Book BNE–ASP nonstop. April can be pricier than shoulder months — buy when 2027 seats open.",
          payer: "james",
        },
      ],
    },
    {
      name: "Alice Springs beds and town",
      lines: [
        {
          item: "Hotel / motel · 3 nights, one double room",
          each: "Midrange room about $150–$220 a night",
          pairLow: 450,
          pairMid: 540,
          pairHigh: 660,
          note: "Two nights before Day 1, one night after Mt Sonder. Share a room. Peak July is dearer than April–May.",
          payer: "salvatore",
        },
        {
          item: "Airport shuttle · both of you, in and out",
          each: "$23 one way or $44 return per adult (valid 1 Apr 2026–31 Mar 2027)",
          pairLow: 88,
          pairMid: 88,
          pairHigh: 88,
          note: "Official Alice Springs Airport shuttle. Book ahead. Taxi from the airport is more.",
          payer: "salvatore",
        },
        {
          item: "Taxi town → Telegraph Station",
          each: "About $20–$25 for the car",
          pairLow: 20,
          pairMid: 25,
          pairHigh: 40,
          note: "One taxi for both of you on Day 1. Or walk ~3 km along the Todd and pay nothing.",
          payer: "salvatore",
        },
        {
          item: "Town meals in Alice",
          each: "Cheap plate ~$20; mid-range dinner for two ~$60–$120",
          pairLow: 220,
          pairMid: 300,
          pairHigh: 400,
          note: "Cover arrival night, the logistics day, and the celebration dinner after Sonder.",
          payer: "salvatore",
        },
      ],
    },
    {
      name: "Parks, camping and Standley",
      lines: [
        {
          item: "NT Parks Visitor Pass · 1 month × 2",
          each: "$45 each",
          pairLow: 90,
          pairMid: 90,
          pairHigh: 90,
          note: "Official interstate visitor pass. A 2-week pass is $30 if your dates fit.",
          payer: "salvatore",
        },
        {
          item: "Larapinta walking-trail fee × 2",
          each: "$125 each (capped)",
          pairLow: 250,
          pairMid: 250,
          pairHigh: 250,
          note: "Official multi-day walk fee. Same price for 6 nights or 20.",
          payer: "salvatore",
        },
        {
          item: "Category B trail camps · 15 nights × 2",
          each: "$10 per adult per night",
          pairLow: 300,
          pairMid: 300,
          pairHigh: 300,
          note: "Wallaby through Jay, Brinkley through Waterfall Gorge, then Finke, Rocky Bar and Redbank.",
          payer: "salvatore",
        },
        {
          item: "Ormiston Gorge · 2 nights × 2",
          each: "$20 per adult per night (Category C)",
          pairLow: 80,
          pairMid: 80,
          pairHigh: 80,
          note: "Arrive Day 15, rest Day 16.",
          payer: "salvatore",
        },
        {
          item: "Standley Chasm unpowered · 2 nights × 2",
          each: "$25.50 first night, $16.50 second, per person",
          pairLow: 84,
          pairMid: 84,
          pairHigh: 84,
          note: "Private camp. Entry to the chasm is included. Showers and a cafe.",
          payer: "salvatore",
        },
      ],
    },
    {
      name: "Transfers and food-drop service",
      lines: [
        {
          item: "3 commercial food-drop containers",
          each: "Larapinta Express 55 L drop from $90 each",
          pairLow: 270,
          pairMid: 270,
          pairHigh: 540,
          note: "Standley, Ellery Creek South, Ormiston. One 55 L box per drop is enough if you pack dense dehydrated food. Budget six boxes if you want more variety. Includes container hire and hotel delivery. Standley’s $5 box fee is in the Express price.",
          payer: "salvatore",
        },
        {
          item: "Parks storeroom key",
          each: "$10 fee + $50 refundable deposit",
          pairLow: 10,
          pairMid: 10,
          pairHigh: 10,
          note: "Needed for Ellery and Ormiston. Deposit is not in the trip total once you return the key.",
          payer: "salvatore",
        },
        {
          item: "Redbank Gorge → Alice transfer · 2 walkers",
          each: "About $190–$250 a seat, or ~$380–$500 for two",
          pairLow: 380,
          pairMid: 440,
          pairHigh: 500,
          note: "Afternoon pickup on Day 20. Larapinta Express lists Redbank from about $190. Other NT Parks-listed operators have been $250/adult or about $380 for two. LTTS paused general 2026 support — book Express, Emu Run or similar for 2027.",
          payer: "salvatore",
        },
      ],
    },
    {
      name: "Food on the trail",
      lines: [
        {
          item: "Dehydrated dinners, breakfasts, snacks · 20 days × 2",
          each: "About $18–$28 per person per day",
          pairLow: 720,
          pairMid: 880,
          pairHigh: 1120,
          note: "Buy in Perth/Brisbane or Alice (Coles, Woolworths, Lone Dingo). Aim 2,800–3,500 kcal/day. Back Country / Radix / supermarket instant meals all work.",
          payer: "salvatore",
        },
        {
          item: "Stove fuel and extras",
          each: "3–4 gas canisters plus electrolytes",
          pairLow: 50,
          pairMid: 60,
          pairHigh: 80,
          note: "No fires on the trail. Share canisters.",
          payer: "salvatore",
        },
        {
          item: "Standley and Ormiston cafe meals",
          each: "Cooked meal about $20–$40",
          pairLow: 40,
          pairMid: 80,
          pairHigh: 120,
          note: "Optional. Nice on the two rest days. Confirm kiosk hours.",
          payer: "salvatore",
        },
      ],
    },
  ] as { name: string; lines: CostLine[] }[],
  notIncluded: [
    "Gear you already own (packs, tent, bags, PLB). Buying a full kit from scratch is another $800–$2,000 each.",
    "Travel insurance and ambulance / evacuation cover — get this. Remote rescue is expensive.",
    "PLB hire if you do not own one, about $50–$80.",
    "Luggage storage in Alice, about $75 a bag with some transfer companies.",
    "Uluru or extra sightseeing after the walk.",
    "2027 price rises. Parks fees, flights and transfer rates can change.",
  ],
};

export const foodDrops = [
  {
    stop: "Standley Chasm",
    day: "Days 5–6",
    covers: "Days 7–11 (Sections 4–6)",
    access: "Private storeroom near the showers. Open 24/7. No Parks key.",
  },
  {
    stop: "Ellery Creek South",
    day: "Day 11",
    covers: "Days 12–15 (Sections 7–9)",
    access: "Locked Parks room in the ablution block. Key + CCTV.",
  },
  {
    stop: "Ormiston Gorge",
    day: "Days 15–16",
    covers: "Days 17–20 (Sections 10–12)",
    access: "Locked Parks room in the main building by the kiosk. Key + CCTV.",
  },
];

export const flights = {
  salvatore: {
    name: "Salvatore",
    from: "Perth (PER)",
    to: "Alice Springs (ASP)",
    options: [
      "Airnorth sometimes flies PER–ASP direct in about 2 hours 40 minutes on selected days. This is the time-saver if the 2027 schedule still runs.",
      "Qantas is the reliable backup: Perth to Adelaide, then Adelaide to Alice. Plan 5–7 hours door to door and a long enough connection.",
      "Virgin Australia usually connects via Adelaide or the eastern capitals. Useful if Qantas is full.",
    ],
  },
  james: {
    name: "James",
    from: "Brisbane (BNE)",
    to: "Alice Springs (ASP)",
    options: [
      "Book Brisbane to Alice Springs nonstop. Qantas and Virgin both fly BNE–ASP in about 3 hours 15 minutes.",
      "Typical recent pattern: Qantas a few days a week (often including Wednesday, Saturday, Sunday) and Virgin on selected days. Confirm the 2027 timetable when it is published.",
      "Aim to land the same afternoon as Salvatore so you share the Alice logistics day.",
    ],
  },
};

export const transfers = [
  {
    name: "Start — Telegraph Station",
    detail: "Taxi about $20–$25 for both of you, or walk about 3 km from town along the Todd. Commercial operators generally do not drop at the eastern trailhead.",
  },
  {
    name: "Finish — Redbank Gorge to Alice",
    detail: "Book a commercial afternoon pickup on Day 20. Budget $380–$500 for two. Larapinta Express, Emu Run, Outback Elite Tours and Outback Tour Services are listed by NT Parks.",
  },
  {
    name: "Recommended 2027 support",
    detail: "Larapinta Express: 55 L food drops from $90 each (book three) plus the Redbank transfer. They deliver empty boxes to your Alice room. LTTS said it would not offer general transfers and drops in 2026 — do not count on that package for 2027 until they say otherwise.",
  },
];

export const gear = [
  { id: "pack", cat: "Carry", item: "65–75 L pack that actually fits a 6 L water carry", essential: true },
  { id: "liner", cat: "Carry", item: "Waterproof pack liner (better than a cover in Hugh Gorge)", essential: true },
  { id: "tent", cat: "Shelter", item: "3-season tent or sturdy tarp + bivy for two", essential: true },
  { id: "mat", cat: "Shelter", item: "Insulated sleeping mat", essential: true },
  { id: "bag", cat: "Shelter", item: "Sleeping bag comfort-rated to at least 0 °C, ideally −5 °C", essential: true },
  { id: "stove", cat: "Cook", item: "Canister or alcohol stove — open fires are illegal on the trail", essential: true },
  { id: "pot", cat: "Cook", item: "Pot, spoon, mug, lighter + backup", essential: true },
  { id: "water", cat: "Water", item: "Bottles / bladder totalling 6 L capacity each", essential: true },
  { id: "treat", cat: "Water", item: "Tablets, filter, or boil plan for tank and surface water", essential: true },
  { id: "plb", cat: "Safety", item: "PLB or satellite messenger (inReach / Zoleo). Phones are not enough", essential: true },
  { id: "firstaid", cat: "Safety", item: "First aid with blister kit, tape, electrolytes, personal meds", essential: true },
  { id: "maps", cat: "Safety", item: "NT Parks section maps (paper) plus this app offline", essential: true },
  { id: "headtorch", cat: "Safety", item: "Headtorch + spare batteries for Sonder dawn", essential: true },
  { id: "boots", cat: "Clothing", item: "Worn-in boots or trail shoes — the quartzite shreds new pairs", essential: true },
  { id: "socks", cat: "Clothing", item: "4–5 pairs hiking socks", essential: true },
  { id: "sun", cat: "Clothing", item: "Long loose sun shirt, trousers, brimmed hat, sunglasses", essential: true },
  { id: "rain", cat: "Clothing", item: "Rain / wind jacket — April can still hold leftover wet-season rain", essential: true },
  { id: "thermal", cat: "Clothing", item: "Thermal top and bottom, puffy, beanie, gloves", essential: true },
  { id: "campshoes", cat: "Clothing", item: "Camp shoes / sandals for waterholes", essential: false },
  { id: "poles", cat: "Optional", item: "Trekking poles (metal tips, no rubber stoppers)", essential: false },
  { id: "gaiters", cat: "Optional", item: "Low gaiters or sock guards for spinifex", essential: false },
  { id: "flynet", cat: "Optional", item: "Fly net — more useful in April–May than mid-winter", essential: false },
  { id: "power", cat: "Optional", item: "Power bank. USB charging exists at Jay Creek, Hugh Gorge, Serpentine Chalet", essential: false },
  { id: "swim", cat: "Optional", item: "Swimmers and a small towel for Ellery, Ormiston, Redbank", essential: false },
];

export const sources = [
  { label: "Plan your Larapinta Trail walk", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/plan-larapinta-trail-walk" },
  { label: "Official sections", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/sections-of-the-larapinta-trail" },
  { label: "Walking grades", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/larapinta-trail-walking-grades" },
  { label: "Water tanks", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/larapinta-trail-water" },
  { label: "Food drops", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/larapinta-trail-food-drops" },
  { label: "Safety advice", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/larapinta-trail-safety-advice" },
  { label: "Current conditions", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/larapinta-trail-current-conditions" },
  { label: "Suggested itineraries", href: "https://nt.gov.au/parks/find-a-park/tjoritja-west-macdonnell-national-park/larapinta-trail/suggested-itineraries" },
  { label: "Walking-trail fees", href: "https://nt.gov.au/parks/bushwalking-hiking/multi-day-walking-trail-fees" },
  { label: "Camping fees", href: "https://nt.gov.au/parks/camping/fees" },
  { label: "NT Parks Visitor Pass", href: "https://nt.gov.au/parks/visitor-pass" },
  { label: "Park bookings", href: "https://parkbookings.nt.gov.au" },
  { label: "Trail GPS (OpenStreetMap relation 3066363)", href: "https://www.openstreetmap.org/relation/3066363" },
  { label: "Larapinta Express food drops", href: "https://larapintaexpress.rezdy.com/600156/food-container-drop" },
  { label: "Standley Chasm camping", href: "https://standleychasm.rezdy.com/462165/unpowered-camping" },
  { label: "Alice Springs Airport shuttle", href: "https://www.alicespringsairport.com.au/traveller/parking-transport/transport-options" },
];

export function getDay(id: string) {
  return days.find((d) => d.id === id);
}

export function getWaypoint(id: string) {
  return waypoints.find((w) => w.id === id);
}
